### ISSUE TITLE
Cannot use apostrophe in a transaction payee

### ISSUE THREAD

**Issue by colindean** [hrj/abandon#139]
When I have

```ledger
2017-02-23 Wendy's
  Expenses:Restaurants    2.76
  amexbce
```

I get this error:

```
Error while parsing /Users/colin/Documents/Finance/Personal/2017/activity.ledger:
[889.17] failure: <eol> expected

2017-02-23 Wendy's

                ^
Input error: Couldn't parse input
```

The obvious workaround is simply to omit the apostrophe, but this is a little bit of a rough edge that has bit me more than once.

**Comment by hrj** [comment]
It should be easy to fix this; thanks for reporting!

**Comment by hrj** [comment]
@colindean If / until this is fixed, as a workaround, you can quote the string whenever there are special characters. For example, the following works right now:

```
2017-02-23 "Wendy's"
  Expenses:Restaurants    2.76
  amexbce
```
---

I had thought this would be an easy change but it is not. (I thought payee string is similar to a comment; gobbled till EOL by the tokeniser. It is not.)

@gerdreiss has made an attempt in PR #144 (much thanks), but I hesitate to add support for special characters to the `identifier` tokeniser, because it percolates to all parsers that use `identifier` (expression and account name parsers).

**Comment by hrj** [comment]
I am not comfortable changing the tokenizer for this case. Quoting the string is the recommended approach; it doesn't require modifications to code and is very general, almost all characters ought to be supported.
