### ISSUE TITLE
Rename transactions and posts consistently

### ISSUE THREAD

**Issue by hrj** [hrj/abandon#64]
IIRC. The code refers to transactions and posts interchangeably.

Per convention, we should change it such that:
* Post refers to a single change in a single account
* Transaction refers to a set of balanced posts

For example,
```
2015/Jan/15
    abc           -100
    xyz
```
should comprise of two posts:
* `abc -100`
* `xyz +100`

and a transaction that comprises of the above two posts.

**Comment by chidu8** [comment]
I will take this up.

**Comment by chidu8** [comment]
I took a quick glance at the task and the source code and I have a few questions (requirements understanding...)

Coming to this task, 
(1) I saw that the Transaction class in Ast.scala has a Seq of "SingleTransaction". Can i rename "SingleTransaction" to "Post" and keep the "Transaction" class as is? Can i rename all occurrences of "SingleTransaction" in all files? 
(2) I also saw a class: "DetailedTransaction".  I'm trying to see if it relates to Post. 
(3) I noticed some new terminology 
case name ~ amount ~ commentOpt => SingleTransaction(name, amount, commentOpt). What does ~ do?

In general, 
(1) Could you please give me a high level explanation of the flow/design/code of the project? Since there are not that many comments, an explanation will help me a lot.

**Comment by hrj** [comment]
1. Yes! Also, `Transaction` contains a field called `transactions` which should be changed to `posts`. Similarly, other fields and variable names need to be changed in the rest of the code to be consistent with the type names.
2. Yes, `DetailedTransaction` should probably be named `DetailedPost`
3. That is a parser combinator. Hit me up on chat if you need help with that.

I have started editing an [overview page](https://github.com/hrj/abandon/wiki/Developer:Overview).
